### ISSUE TITLE
Fix Butterschuß

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#1]
## Beschreibung
Der Timer für den Cooldown des Raketenwerfers wird beim Szenenwechsel nicht zurückgesetzt
## Reproduzierbarkeit
- Starte das Spiel
- warte auf spielende
- Im winscreen kann man den Raketenwerfer nicht mehr benutzen

**Comment by Assertores** [comment]
fixed with b7a84efc2af4c8890fbed2ed53896c30134022f8
