### ISSUE TITLE
Some characters don't shoot directly upwards if the weapon points upwards

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#10]
## Beschreibung
Einige Character scheinen nicht direkt nach oben zu schießen wenn man nach oben schießt
-Bullets spawnen leicht neben dem Pfeil

## Reproduzierbarkeit
- spiel starten
- nach oben zielen 
-Bullets/Rockets spawnen neben der Waffe

Bullets/Rockets spawnen vorne an der Waffe am Lauf

**Comment by Assertores** [comment]
fixed in 2fa6c48a537616c7c15a696d92869d1b3c342b72
