### ISSUE TITLE
Waffe nicht mehr bewegen können

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#13]
## Beschreibung
-die waffe locked an einer Position und lässt sich nicht mehr bewegen

## Reproduzierbarkeit
- Siehe Kommentare
-funktioniert wieder bei respawn

Die waffe soll sich ganz normal drehen zu jeder Zeit

**Comment by Assertores** [comment]
das sprite wird aber noch geflipt nur nicht mehr gedreht

**Comment by MaxRaabe** [comment]
ba0c14a6811b6e87c66daf9b25c4aa54826bda1a
