### ISSUE TITLE
CSV Datei verursacht fehler beim Winscreen

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#14]
## Beschreibung
Pillars spawnen nicht und CSV datei kann nicht gefunden/erstellt werden

## Reproduzierbarkeit
- Spiele ein Spiel
- Komme in den Winscreen

Überprüfung durch Check ob Directory DATA vorhanden ist

**Comment by Assertores** [comment]
fixed in e17760032a686670a8038adaaa0cc2a4eaba990d
