### ISSUE TITLE
Assists werden nicht richtig getracked

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#16]
## Beschreibung
Die assists sind viel zu hoch und korrelieren nicht zu den eigentlich assists.

## Reproduzierbarkeit
- Starte das Spiel
- Join Game
-Spiele gegen einen Spieler
-Beende das Spiel
-zu viele Assists

-In einem 1v1 sollte es keine Assists geben

**Comment by Assertores** [comment]
fixed in e86ff76ded142cb3dd50dd4d9621d5c6fa4ed7bd
