### ISSUE TITLE
Playerstats werden nicht zurückgesetzt nach WS

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#34]
## Beschreibung
Playerstats werden nicht zurückgesetzt

## Reproduzierbarkeit
- starte Spiel 
- komme in den Winscreen
- komme in das MainMenu
-starte Spiel nochmal

//playerstats sollten auf 0 gesetzt werden

**Comment by Assertores** [comment]
fixed in da62e9b9ac070923f00b71c4adba5d590b18a7c1
