### ISSUE TITLE
Player keeps shooting when entering the game

### ISSUE THREAD

**Issue by MaxRaabe** [Assertores/ProjectAres#7]
## Beschreibung
when the player shoots at the start button and doesn't press the shoot button right after that he is automatically shooting

## Reproduzierbarkeit
- start game
- shoot at start button
- start the play mode
- player shoots automatically

the player doesn't shoot automatically

**Comment by Assertores** [comment]
fixed with 29781bccfab174fd9b6f10080b01f3957b13285f
